### PR TITLE
Fix code quality tools

### LINKED ISSUE #150: incompatible path on baseline for phpstan (alone) and grumphp.
**Describe the bug**
`composer fop_check` (grumphp) and `vendor/bin/phpstan` handle the .devtools/phpstan_baseline.neon with different path root.

So if an error on phpstan_baseline.neon is reported with a correct path for phpstan standalone, it's ok for grumphp.
The opposite it also true.

```neon
parameters:
	ignoreErrors:
		-
			message: "#^Call to an undefined method Symfony\\\\Component\\\\Console\\\\Application\\:\\:getKernel\\(\\)\\.$#"
			count: 1
			path: src/Commands/CheckServiceContainer.php

# That's fine, dump() can handle multiple values - This is not an error. https://github.com/symfony/var-dumper/blob/3.4/Resources/functions/dump.php
		-
			message: "#^Function dump invoked with 2 parameters, 1 required\\.$#"
			count: 1
			path: ../src/Commands/Configuration/Export.php
```

with this baseline, first path is ok for grumphp, not phpstan directly.
second path it not ok for grumphp but ok for phpstan.

Maybe we could move the baseline file at the root.

No one reported this recent problem.
Do you use grumphp on pre-commit hook (or `composer fop_check`) ? @okom3pom @Kaudaj ?

### PR DESCRIPTION
**Pull request by tom-combet**
Fixes #150 (and closes #203?).

Fixed issues:
• PHP-CS-Fixer workflow step wasn't using our custom configuration file.
• PHPStan was old... very old...
• GrumPHP was overwriting our level setting and checking dot files ([where PHPStan doesn't](https://github.com/phpstan/phpstan/discussions/6180#discussioncomment-1784130)).

### CODE REVIEW

**Comment by nenes25** [comment]
Good job :+1:  !
Do we need to check an other thing than that the automatic workflows are good ?

**Comment by SebSept** [comment]
I think we need to test on our machines..
I'd like to do it.

**Comment by Kaudaj** [comment]
Yes, every reviewer should check on his side if GrumPHP works fine by running `composer fop_check`. You should have an "All Good" output.

**Comment by SebSept** [comment]
I will also make a commit in my ide

File: src/Commands/Container/ContainerCheck.php [hunk 1]
```diff
@@ -67,8 +66,6 @@ protected function execute(InputInterface $input, OutputInterface $output): int
             ) {
                 try {
                     $this->getContainer()->get($serviceId);
-                } catch (NotImplementedException $notImplementedException) {
```
Comment (SebSept) [inline src/Commands/Container/ContainerCheck.php:70]: What did you do here ?

File: src/Commands/Environment/EnvironmentDebug.php [hunk 2]
```diff
@@ -110,18 +112,18 @@ private function displayMessageIfDevModeEnvIsSet(): void
...
 
             !$custom_defines_file_exists
                 ?: $this->io->note("'$custom_defines_file_path' exists, check it.");
 
             $evaluatedDevMode = (bool) getenv('PS_DEV_MODE');
             $this->io->note(
-                'The current value of PS_DEV_MODE environment variable is "'.getenv('PS_DEV_MODE').'"'.PHP_EOL
-            .'So the PS_DEV_MODE may be '.($evaluatedDevMode ? 'enabled' : 'disabled').'.'
+                'The current value of PS_DEV_MODE environment variable is "' . getenv('PS_DEV_MODE') . '"' . PHP_EOL
+            . 'So the PS_DEV_MODE may be ' . ($evaluatedDevMode ? 'enabled' : 'disabled') . '.'
```
Comment (SebSept) [inline src/Commands/Environment/EnvironmentDebug.php:126]: cs-fixer was not ran on this file ?

**Review by SebSept — APPROVED** [review]
Nice, it looks like you saved the old 😄 

- So you reported than grumphp overrides the default level, good catch. 
Maybe we can add a note in phpstan.neon about that. (and also in grumphp).
- And that .dotfiles option also need to be specified.

I tested on 
- git pre-commit
- composer run fop_check
- ./vendor/bin/<phpstan|php-cs-fixer>
- commit in phpstorm.
Everything was fine 👍🏼 

for testers, don't forget that grumphp only checks files that are added to the git index (ready to commit).

**Comment by SebSept** [comment]
for testers, don't forget that grumphp only checks files that are added to the git index (ready to commit).

File: src/Commands/Environment/EnvironmentDebug.php (hunk 2 above)
Comment (Kaudaj) [reply src/Commands/Environment/EnvironmentDebug.php:126]: Hmm yes, it was, why?

File: src/Commands/Container/ContainerCheck.php (hunk 1 above)
Comment (Kaudaj) [reply src/Commands/Container/ContainerCheck.php:70]: PHPStan reported this exception as never thrown. Is he wrong?

**Comment by Kaudaj** [comment]
> So you reported than grumphp overrides the default level, good catch.
> Maybe we can add a note in phpstan.neon about that. (and also in grumphp).

I already wrote a comment in grumphp configuration file. As it concerns only GrumPHP execution, I don't think it's necessary to add a note in phpstan configuration. Did you mean add a comment there too or did I misunderstand?

> And that .dotfiles option also need to be specified.

Same here.

**Comment by SebSept** [comment]
> I already wrote a comment in grumphp configuration file. As it concerns only GrumPHP execution, I don't think it's necessary to add a note in phpstan configuration. Did you mean add a comment there too or did I misunderstand?

Yes, that's what I mean.
Someone may change the value in in phpstan.neon.dist then run `fop_check` or commit.

**Comment by Kaudaj** [comment]
Ah ok I see, I'll add this 👍

File: grumphp.yml.dist [hunk 3]
```diff
@@ -2,7 +2,10 @@ grumphp:
   tasks:
     phpcsfixer:
       config: .php_cs-fixer.dist.php
-    phpstan: ~
+    phpstan:
+      level: 5 # Needed because Grum overwrite level at 0 by default in 0.19.1 version
```
Comment (SebSept) [inline grumphp.yml.dist:6]:
```suggestion
      level: 5 # Needed because Grumphp overwrites level at 0, by default in 0.19.1 version
```

File: phpstan.neon.dist [hunk 4]
```diff
@@ -1,18 +1,18 @@
...
   paths:
+    # If dotfile path added, need to be added in grumphp.yml.dist too
     - ./
-  excludes_analyse:
+  excludePaths:
     - vendor/
     - .devtools/phpstan/stubs/
   reportUnmatchedIgnoredErrors: true
-  level: 5
+  level: 5 # If changed, need to be changed in grumphp.yml.dist too
```
Comment (SebSept) [inline phpstan.neon.dist:9]:
```suggestion
  level: 5 # If changed, needs to be changed in grumphp.yml.dist too
```

**Comment by SebSept** [comment]
can anyone else confirm it's ok with their config ?
@nenes25, @okom3pom, @jf-viguier

**Comment by SebSept** [comment]
I've just re tested, work fine both on command line and inside phpstorm :)

**Comment by SebSept** [comment]
> can anyone else confirm it's ok with their config ? @nenes25, @okom3pom, @jf-viguier

ping

**Review by nenes25 — APPROVED** [review]
Everything is fine for me too :smile:

**Comment by SebSept** [comment]
You "just" need to resolve the conflicts @tom-combet .

**Comment by tom-combet** [comment]
@SebSept Done, thanks for validating it!
